#服务端口
server:
  port: 8081
spring:
  #设置json返回数据的格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    #服务名
    name: service-edu
  profiles:
    #环境设置 dev test prod
    active: dev
  datasource:
    #设置数据库环境
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: yyx20021215
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    database: 0
    host: 47.110.249.72
    port: 6379
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
mybatis-plus:
  configuration:
    #mybatis-plus日志设置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  hystrix:
    #开启熔断机制
    enabled: true
    #设置全局日志级别
    #logging:
    #level:
    #root: debug
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000